### ISSUE TITLE
Is there a compatibility issue with Django 1.9+ ?

### ISSUE THREAD

**Issue by whelks-chance** [dadoeyad/grappelli-side-menu#1]
Seems to work fine with 1.8, but 1.9 throws:

"Invalid template library specified. ImportError raised when trying to load 'grappelli_menu.templatetags.admin_apps': cannot import name get_models"

**Comment by dadoeyad** [comment]
I haven't updated the library since a long while.
Please feel free to open a pull request for the solution and I'll accept it :)

**Comment by evrenesat** [comment]
I can't find it's usage and just removed that import and everything got fixed.

https://github.com/dadoeyad/grappelli-side-menu/blob/master/grappelli_menu/templatetags/admin_apps.py#L3

**Comment by dadoeyad** [comment]
Just fixed the issue with a new release.
Thanks for reporting the issue!
